// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-InMobi",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-InMobi", targets: ["AATKit-InMobi"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-InMobi",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATInMobiAdapter",
                    "AATInMobiSDK",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-InMobi"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATInMobiAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/AATInMobiAdapter.zip",
            checksum: "eb4c5e4d6ca6ca51ea5719d9f22a7299d5d7e1485a84273ac56394779f91c0b9"
        ),
        .binaryTarget(
            name: "AATInMobiSDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/InMobiSDK.zip",
            checksum: "19c90c71ae9d02ecab0e0999c5238191eaa8271d6d933ef7b2811a8adbe7c75b"
        ),
    ]
)
