// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-InMobi",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-InMobi", targets: ["AATKit-InMobi"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta3"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-InMobi",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATInMobiAdapter",
                    "AATInMobiSDK",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-InMobi"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATInMobiAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/AATInMobiAdapter.zip",
            checksum: "6972e30bfd000a31931ce51180a4123245bfe43916b3de8cdedfae12f4259b54"
        ),
        .binaryTarget(
            name: "AATInMobiSDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/InMobiSDK.zip",
            checksum: "8e036e4e8749814e82f235dc513cc7eab300a083aac922a8b5d8f4fe0cc45352"
        ),
    ]
)
